trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'

- script: python -m pip install --upgrade pip
  displayName: 'Upgrade pip'

- script: pip install -r requirements.txt
  displayName: 'Install dependencies'

# (Optional) run tests if you add them
- script: |
    pip install pytest
    pytest -q
  displayName: 'Run tests'

- script: |
    echo "Build succeeded"
  displayName: 'Build/verify'
